# Docker Data Engineering Image
# Maintainer: bchwtz

FROM jupyter/all-spark-notebook:13b866ff67b9

USER root

RUN apt-get update && apt-get install -y \
    ssh \
    pdsh \
    htop \
    tmux \
    vim

ADD ./script/setup_hadoop.sh /
RUN chmod +x /setup_hadoop.sh
RUN /setup_hadoop.sh

ADD ./config/hadoop/core-site.xml /opt/hadoop-3.3.0/etc/hadoop/
ADD ./config/hadoop/hdfs-site.xml /opt/hadoop-3.3.0/etc/hadoop/
ADD ./config/hadoop/mapred-site.xml /opt/hadoop-3.3.0/etc/hadoop/
ADD ./config/hadoop/yarn-site.xml /opt/hadoop-3.3.0/etc/hadoop/

ADD ./script/setup_userprofile.sh /
RUN chmod +x /setup_userprofile.sh

USER jovyan
RUN /setup_userprofile.sh


EXPOSE 8888 4040 9870 8088



#COPY . /app
#RUN make /app
#CMD python /app/app.py